CREATE TABLE Account(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME VARCHAR2(50) UNIQUE NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	PASSWORD VARCHAR2(128) NOT NULL,
	SIGN_UP_DATE TIMESTAMP,
	LAST_SIGN_IN TIMESTAMP,
	FAILED_LOGIN_COUNT INTEGER DEFAULT 0,
	LOCKED INTEGER DEFAULT 0
);

CREATE TABLE User_Session(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SESSION_KEY VARCHAR2(50) NOT NULL,
	USER_ID INTEGER NOT NULL,
	IP VARCHAR2(15) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	AUTOLOGIN INTEGER DEFAULT 0,
	ENCRYPTED_AUTOLOGIN_KEY VARCHAR2(255),
	ENCRYPT_KEY BLOB,
	IV_KEY BLOB,
	FOREIGN KEY(USER_ID) REFERENCES Account(ID)
);

CREATE TABLE Challenge (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_ID INTEGER NOT NULL,
	NAME VARCHAR2(255) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	DIFFICULTY INTEGER NOT NULL,
	TECHNOLIGIES VARCHAR2(2),
	UPLOAD_DATE TIMESTAMP NOT NULL,
	BANNER_PATH VARCHAR2(255),
	FOREIGN KEY(USER_ID) REFERENCES Account(ID)
);

INSERT INTO Account (USERNAME, EMAIL, PASSWORD, SIGN_UP_DATE, LAST_SIGN_IN)
Values ("Test User 1", "testuser1@test.com", "password", current_timestamp, current_timestamp)

INSERT INTO User_Session (SESSION_KEY, USER_ID, IP, CREATION_DATE)
Values ("sIdIyofEKJXXFaAUNmUQpvkZJYPEDFIoBRvSoTLMjecZnajeCl", 1, "127.0.0.1", current_timestamp)